---

devilbox_info:
  name: stackedit
  description: Stackedit is in-browser Markdown editor
  author: "Laurent Laville"
  github: llaville
  license: MIT
  min_devilbox_version: v1.0.1
  tags:
    - Markdown
    - Editor
